### ISSUE TITLE
BUG - Simulations unable to restart from checkpoint files

### ISSUE THREAD

**Issue by mb2055** [OpenBioSim/somd2#20]
The option  `restart=True` is currently non-functional, throwing the error `SireBase::missing_property: None of the contained forcefields have a property called config. Available properties are [ energy_trajectory, time, space, ensemble ]`. This results from `SOMD2` attempting to compare the streamed checkpoint file with its current configuration (needed to ensure that the requested restart from checkpoint is sensible) and being unable to find either the old configuration or the old lambda value in the porperties of the streamed system. 

Should be a simple fix - both `lambda` and `config` need to be added to the shared property of the system before it is saved to checkpoint.

**Comment by lohedges** [comment]
Closed by #21
