### ISSUE TITLE
[BUG] GPU utilisation unstable during bound runs

### ISSUE THREAD

**Issue by akalpokas** [OpenBioSim/somd2#8]
## Describe the bug
GPU utilisation seems to be unstable during FEP runs for the bound leg (protein + ligand + water, ~63K atoms) for a sample simulation in TYK2 benchmark. This results in slow MD simulations for this leg as the GPU usage jumps between 0 to 100% rapidly which can be seen in this `nvtop` output screenshot:

![image](https://github.com/OpenBioSim/somd2/assets/23294952/d032024b-1488-438a-97af-8a8f914e3788)

For the free leg (ligand + water only,  ~3.5K atoms) GPU is properly utilised (drops indicate points at which the engine starts a new simulation with a new λ value:

![image](https://github.com/OpenBioSim/somd2/assets/23294952/8e1d2af5-1445-44b3-be93-1f8b4a84cde4)

## To reproduce

Run provided input files with:

```shell
export NUMEXPR_MAX_THREADS=8
export CUDA_VISIBLE_DEVICES=0

somd2 ejm31-ejm50.bss --log-level trace
```

Full reproducible example also available in [somd2 examples repository.](https://github.com/OpenBioSim/somd2_examples/tree/main/tyk2/)

## Things I have tried so far
1. Increasing the number of CPU threads to 30 - doesn't seem to change much
2. Run a multi-GPU simulation - same behaviour on each GPU
3. Run on a different machine - on my laptop the GPU utilisation is spiking between 50-100%, instead of 0-100%

## Input files
[inputs.tar.gz](https://github.com/OpenBioSim/somd2/files/13365923/inputs.tar.gz) and [somd2 examples repository.](https://github.com/OpenBioSim/somd2_examples/tree/main/tyk2/)

## Environment information:
SOMD2 version: `0.1.dev169+ga642d47`
BioSimSpace version: `2023.5.0.dev`
Sire version: `2023.5.0.dev`

**Comment by lohedges** [comment]
Hmm, what is the time interval on the x-axis of your plot? Is this the full length of your run, or just the max of the sliding window? 

When running locally I see the following:

* Small dips from about 100 to 75/50% at regular intervals. I _think_ these are when it is computing energies at the different lambda values at the `energy_frequency`(1ps by default) and when saving frames at the `frame_frequency` (20ps by default).
 * Large dips down to 0% at the `checkpoint_frequency` when it is saving checkpoint files and the current energy trajectory.
 
 (I"m just running on my laptop, so some periodic throttling is going on too.)
 
 For reference, the full width of my output is about 70 seconds. I see something like this:
 
![nvtop](https://github.com/OpenBioSim/somd2/assets/648557/f56109eb-3bcd-4e49-91e8-2daa10b9b40a)

The large dip about 3/4 of the way to the right (17s on the axis) is exactly when a block finished and it performed a checkpoint.

Is the overall runtime worse than you'd expect for this system? For example, in comparison to what you'd get with SOMD1.

`NUMEXPR_MAX_THREADS` should have no impact. Also, the `max_threads` configuration option is only relevant for the CPU platform.

**Comment by akalpokas** [comment]
The time interval for my plots is the max of the sliding window (my version on nvtop doesn't add axis labels unfortunately), which is around 2 minutes for these plots. The GPU utilisation seems to be directly related to the the frequency of energy is computed as you have suggested. This is how the GPU performance looks like when `energy_frequency` is set to `10ps`:
![image](https://github.com/OpenBioSim/somd2/assets/23294952/583f00db-4cd8-41c1-90bf-0d5f65a86c28)

This is how the GPU performance looks like when `energy_frequency` is set to `100ps` (large dips to 0% at the `checkpoint_frequency`):
![image](https://github.com/OpenBioSim/somd2/assets/23294952/001d2c67-19bc-41d3-b614-646514d45bd4)

Doing some rough calculations this translates to the following performance on my machine:
- `energy_frequency = 1ps (default)` = 90 ns/day
- `energy_frequency = 10ps` = 197 ns/day
- `energy_frequency = 100ps` = 234 ns/day

Thanks for your help with this!

**Comment by lohedges** [comment]
No problem. Some of the operations can be done in the background while the next block of the dynamics of progressing, e.g. copying coordinates back to the Sire system. Unfortunately, computing the energy and different lambda values requires the current context, which can't be copied, so is an operation that stalls the dynamics. Some tuning will be required to choose an appropriate `energy_frequency` for optimal sampling.

**Comment by chryswoods** [comment]
Just to add to this, the way the free energy code works is that lambda exists outside the context. Every `energy_frequency` steps the dynamics is stopped, and the forcefield parameters for perturbable atoms are then changed by calling the appropriate OpenMM functions. The GPU then calculates the new potential energy for these parameters, which is returned. We repeat this for each perturbed lambda value that is of interest.

As Lester says, this has to be done inline in the OpenMM context, i.e. dynamics can't resume until all the energies for all the peturbed lambda values are calculated.

While this can slow things down, the benefit is that we aren't calculating these energies or dealing with lambda at each step of dynamics. We are able to use the native (standard) OpenMM Force objects, which we think are the fastest (and support things like PME easily).

Part of tuning will be picking an `energy_frequency` that maximises the number of energy values to get a statistically meaningful free energy average, while having lots of sampling. I suspect tuning will be based on choosing a number of energy snapshots you want, a desired simulation runtime, and then picking an `energy_frequency` that runs as many MD steps as possible to achieve N energy updates per M minutes of dynamics.

It would also be worth investigating whether evaluating the energy at more than 2-3 lambda values is worth the cost (the cost of the energy calculation will scale linearly with the number of lambda windows evaluated). It may be more efficient to evaluate the energy at a smaller number of lambda windows and have more dynamics per day for each of those windows. You could also envisage having one frequency to update the energy just for neighbouring lambda windows, and then a lower frequency for updating the energy across all lambda windows. Lots to play with and tune :-)

I am interested that your GPU usage drops to zero when the parameters are being updated and the energy calculated. I would expect it to still show some usage, as the time should be dominated by the time taken by the GPU to calculate the new energy. This may be worth exploring at some point.

However, as you've shown, running a 10ps update frequency gets close to the raw performance of OpenMM (I guess somewhere north of 240 or 250 ns / day based on the 100ps value).

**Comment by jmichel80** [comment]
In SOMD1 the overheads of evaluating ~10 lambda energies every ~100 timesteps is small (don’t have the exact figures). 
it would be useful to check how overheads grow with the number of lambda values. I can think of use cases with around 100 values. Saving datapoints every 10 ps feels a little on the low side. 
wouldn’t it be possible to cache a context for repeatedly evaluating a single point energy at different lambda values?

**Comment by lohedges** [comment]
Yes, it's strange that it dips to zero. I didn't see that locally, apart from when checkpointing, which is the end of a dynamics block.

It's not possible to copy a context since it can only be assigned to a single platform. Perhaps there is another way to cache, e.g. recreating the context state on the CPU, then doing the energy calculations using that while the other context runs on the GPU?

(Originally we thought that we'd pass in a context to the runner, then clone for each lambda window. This isn't possible since the platform is already assigned and isn't modifiable. We just create contexts as needed at runtime.)

**Comment by akalpokas** [comment]
The GPU usage dips to 0% specifically on a faster GPU (RTX 3090) when I run the simulation remotely on my workstation, whereas locally on my laptop GPU (RTX 3060 Laptop) it dips only to 50% and I basically see the same nvtop profile as Lester does. I assume this is because the faster GPU finishes the specific task it's allocated at the point where lambda energies are calculated more rapidly, and spends more time idling around until the dynamics can then resume fully.
